# Generated by Django 5.2 on 2025-04-14 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OLevelSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OLevelMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('student', models.ForeignKey(limit_choices_to={'education_level': 'O'}, on_delete=django.db.models.deletion.CASCADE, to='core.student')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.term')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olevel.olevelsubject')),
            ],
            options={
                'unique_together': {('student', 'subject', 'term')},
            },
        ),
    ]
