# Generated by Django 5.2 on 2025-04-14 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olevel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='olevelmark',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
